server {
    listen 80;
    index index.php index.html;
    server_name localhost;

    client_max_body_size 1G;
    send_timeout 300s;
    root /var/www/public;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass app:9000;
        fastcgi_index index.php;

        fastcgi_connect_timeout 300s;
        fastcgi_send_timeout    300s;
        fastcgi_read_timeout    300s;

        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
    }
}
